export const COMPANY = {
  name: 'Artı Oluşum Sigorta',
  short: 'AOL Sigorta',
  slogan: 'Memnuniyetiniz için uzman bir takım',
  hq: {
    label: 'Ankara — Merkez',
    phone: '+90 312 468 34 50',
    addr: 'Aziziye Mah. Cinnah Cad. No:50/12, Çankaya / Ankara'
  },
  branch: {
    label: 'Denizli — Şube',
    phone: '+90 258 264 68 69',
    addr: 'Sümer Mah. 2482/2 Sok. Sky City No:4/1 D:73, Merkezefendi / Denizli'
  },
  email: 'info@aol.gen.tr',
  quoteEmail: 'ortak@aol.gen.tr',
  hours: 'Hafta içi 09:00 – 18:00 · Cumartesi 09:00 – 14:00',
  domain: 'aol.gen.tr'
};

export const STATS = [
  { n: '30',  s: 'yıla yakın', l: 'Sektör deneyimi' },
  { n: '22',  s: 'sigorta şirketi', l: 'Aktif acentelik' },
  { n: '12',  s: 'ana kategori', l: 'Ürün portföyü' },
  { n: '5',   s: 'şube', l: 'Türkiye genelinde' },
];

export const PRODUCTS = [
  {
    id: 'kasko',
    idx: '01',
    title: 'Kasko Sigortası',
    kicker: 'Aracınız için tam koruma',
    desc: 'Kasko Sigortası, herhangi bir motorlu kara taşıtının sigortalı kişinin iradesi dışında araç hareket halindeyken ya da dururken hasara uğraması, çalınması, yanması ve kaza gibi durumlarda sigorta sahibine tazminat ödenmesini sağlar.',
    body: [
      'Kasko Sigortası, zorunlu Trafik Sigorta\'sının aksine karşı taraftaki aracı değil; sigorta sahibinin kendi aracını güvence altına almasını sağlar ki bu durum Kasko ve Trafik sigortaları arasındaki farktır.',
      'İsteğe bağlı sigortalar arasında yer alan Kasko Sigortası\'nın avantajlı ve kapsamlı sigorta poliçeleriyle birlikte güçlendirebilir, araba sürme keyfinize güveni ve huzuru ekleyebilirsiniz.',
    ],
  },
  {
    id: 'trafik-sigortasi',
    idx: '02',
    title: 'Trafik Sigortası',
    kicker: 'Zorunlu üçüncü şahıs güvencesi',
    desc: 'Trafik Sigortası genellikle Kasko Sigortası ile karıştırılır. Trafik Sigortası\'nın Kasko Sigortası\'ndan farkı, sigortayı yaptıranın aracının değil; karşı tarafın hasar gören aracının zararlarının karşılanmasına yönelik zorunlu bir sigortadır.',
    body: [
      'Trafik Sigortası\'nın kapsamında; sigortacı, poliçede tanımlanan motorlu aracın işletilmesi sırasında, bir kimsenin ölümüne veya yaralanmasına veya bir şeyin zarara uğramasına sebebiyet vermiş ise Karayolları Trafik Kanunu\'na göre, işletene düşen hukuki sorumluluğu, zorunlu sigorta limitlerine kadar temin edilir.',
      'Meydana gelen bir kazada zararın önlenmesi veya azaltılması amacıyla, sigorta ettirenin yapacağı makul ve zorunlu masraflar sigortacı tarafından karşılanır.',
      'Trafik Sigortası ile Artan Mali Sorumluluk (İMM), Koltuk Ferdi Kaza (KFK), Hizmet – Trafik teminatları da bir arada alınabilmektedir.',
    ],
  },
  {
    id: 'ferdi-kaza',
    idx: '03',
    title: 'Ferdi Kaza Sigortası',
    kicker: 'Kaza anında finansal güvence',
    desc: 'Sigortalının veya yakınlarının kaza sonucu hayatını kaybetmesi veya kalıcı sakatlığı söz konusu olduğunda, belirtilen limitler doğrultusunda sigorta bedeli menfaatdarlara veya kanuni hak sahiplerine ödenir.',
    body: [
      'Bir kaza sonucu vefat halinde poliçede belirtilen sigorta bedeli, poliçede gösterilen menfaat sahiplerine, yoksa kanuni hak sahiplerine ödenir.',
      'Bir kaza sonucunda derhal veya en geç iki yıl içerisinde kalıcı sakatlık hali ortaya çıkarsa, sakatlığın türüne göre sigorta bedelinin belirli bir oranı sigortalıya ödenir.',
      'Kaza sonucunda geçici bir süre çalışamayacak duruma düşüldüğünde, sigortalının gündelik tazminat talebi poliçe kapsamı ve şartları dahilinde karşılanır.',
      'Bu teminatın alınması ile kaza gününden itibaren bir sene zarfında poliçede belirtilen limitler dahilinde doktor ücreti, ilaç, hastane ve diğer tedavi masrafları (nakil ücretleri hariç) karşılanır.',
    ],
  },
  {
    id: 'hayat-sigortasi',
    idx: '04',
    title: 'Hayat Sigortası',
    kicker: 'Sevdikleriniz için uzun vadeli güvence',
    desc: 'Hayat Sigortası, beklenmedik risklere karşı sizin ve ailenizin yaşam standartlarının aynı koşullarla korunarak devam etmesini sağlayan bir sigorta ürünüdür.',
    body: [
      'Yıllık Hayat Sigortası ile temel olarak yaşam kaybı riski teminat altına alınmaktadır. Sigorta kapsamında; vefat teminatı, kaza sonucu vefat teminatı, kaza sonucu tam ve kısmi maluliyet teminatı, kaza sonucu tedavi masrafları teminatı, hastalık sonucu tam ve daimi maluliyet teminatı, kaza sonucu hastane gündelik tazminat teminatı bulunmaktadır.',
      'Yaşam kaybı durumunda ödenecek vefat tazminatı ile geçiminizi sağladığınız ailenizin gelir kaybı yaşamasını engelleyebilirsiniz, çocuklarınızın eğitimlerini tamamlamasını garantileyebilirsiniz, ailenize yaşayacakları sıkıntılı dönemde gerekli finansal desteği sunabilirsiniz.',
      'Kaza sonucu riskin oluşması durumunda ödenecek tazminat ile bakım ve tedavi masraflarınızı karşılayabilirsiniz, çalışamamanızdan kaynaklanabilecek gelir kayıplarınızı telafi edebilirsiniz, yaşam ortamınızda gerekebilecek değişiklikleri yapabilirsiniz.',
    ],
  },
  {
    id: 'konut-sigortasi',
    idx: '05',
    title: 'Konut Sigortası',
    kicker: 'Eviniz için kapsamlı koruma',
    desc: 'Konut Sigortası ve İşyeri sigortası ürünlerimiz, eviniz veya işyerinizin içindeki eşyaları, makinaları, emtiaları yangından hırsızlığa, depremden su baskınına kadar pek çok riske karşı koruma altına alan geniş kapsamlı ve "kişiye ve kuruma özel" bir paket sigorta uygulamasıdır.',
    body: [
      'Evinizin veya İşyerinizin içerisindeki eşyaların, mallarınızın kullanılamaz veya oturulamaz hale geldiği durumlarda, taşınma veya enkaz kaldırma gibi giderler sizi mağdur edebilir. Ayrıca evinizde veya işyerinizde oluşabilecek hasarlar yüzünden kiracınızı taşınmak zorunda bırakabilir, bu nedenle kira gelirinizden mahrum olabilirsiniz. Firmamızın, sunmuş olduğu Konut Sigortası ve İşyeri Sigortası ürünleri ile sizi buna benzer oluşabilecek birçok yükten kurtarır.',
      'Konut Sigortası, tek bir poliçe ile birçok durum için güvence sunmaktadır. Yangın, deprem, fırtına, sel ve su baskını gibi durumlar sonucu evdeki eşyaların teminat altına alınması konut paket sigortasının kapsamındadır.',
      'Konut Sigortası kapsamında sigortalılarımızın hayatını kolaylaştıracak ve herhangi bir ek ücret istemeden verilen asistans hizmetlerini de sunuyoruz. Bunlar; konutta meydana gelen hasar sonucu oluşan tesisat ve elektrik sorunlarının tamiratından, doktor veya ambulans gönderilmesine, otel hizmetine veya konutun fatura ödemelerine destek vermeye kadar, geniş bir yelpazede bulunmaktadır.',
    ],
  },
  {
    id: 'isyeri-sigortasi',
    idx: '06',
    title: 'İşyeri Sigortası',
    kicker: 'İş alanınız için bütünleşik güvence',
    desc: 'Konut Sigortası ve İşyeri sigortası ürünlerimiz, eviniz veya işyerinizin içindeki eşyaları, makinaları, emtiaları yangından hırsızlığa, depremden su baskınına kadar pek çok riske karşı koruma altına alan geniş kapsamlı ve "kişiye ve kuruma özel" bir paket sigorta uygulamasıdır.',
    body: [
      'Evinizin veya İşyerinizin içerisindeki eşyaların, mallarınızın kullanılamaz veya oturulamaz hale geldiği durumlarda, taşınma veya enkaz kaldırma gibi giderler sizi mağdur edebilir. Ayrıca evinizde veya işyerinizde oluşabilecek hasarlar yüzünden kiracınızı taşınmak zorunda bırakabilir, bu nedenle kira gelirinizden mahrum olabilirsiniz. Firmamızın, sunmuş olduğu Konut Sigortası ve İşyeri Sigortası ürünleri ile sizi buna benzer oluşabilecek birçok yükten kurtarır.',
      'Konut Sigortası, tek bir poliçe ile birçok durum için güvence sunmaktadır. Yangın, deprem, fırtına, sel ve su baskını gibi durumlar sonucu evdeki eşyaların teminat altına alınması konut paket sigortasının kapsamındadır.',
      'Konut Sigortası kapsamında sigortalılarımızın hayatını kolaylaştıracak ve herhangi bir ek ücret istemeden verilen asistans hizmetlerini de sunuyoruz. Bunlar; konutta meydana gelen hasar sonucu oluşan tesisat ve elektrik sorunlarının tamiratından, doktor veya ambulans gönderilmesine, otel hizmetine veya konutun fatura ödemelerine destek vermeye kadar, geniş bir yelpazede bulunmaktadır.',
    ],
  },
  {
    id: 'dask',
    idx: '07',
    title: 'DASK',
    kicker: 'Zorunlu deprem güvencesi',
    desc: 'Ülkemiz yüksek riskli deprem kuşaklarından birinde yer almaktadır. Depremin doğrudan neden olduğu maddi zararlar ile deprem sonucu meydana gelen yangın, infilak, dev dalga (tsunami) veya yer kaymasının kendinize ve sevdiklerinize verebileceği maddi zararların karşılanabilmesi için vakit kaybetmeden Zorunlu Deprem Sigortanızı yaptırmanızı öneriyoruz. Zorunlu Deprem Sigortası Doğal Afet Sigortaları Kurumu (DASK) tarafından sunulmaktadır.',
    body: [],
  },
  {
    id: 'saglik-sigortasi',
    idx: '08',
    title: 'Sağlık Sigortası',
    kicker: 'Özel Sağlık & Tamamlayıcı Sağlık',
    desc: 'Özel Sağlık Sigortası, dilediğiniz doktor ya da sağlık kurumunu seçme özgürlüğü sağlar. Sigortalıların herhangi bir kaza ya da hastalık sonucu ortaya çıkan ayakta ya da yatarak teşhis ve tedavilerine ait masraflar, yurtiçinde veya dünyanın neresinde olurlarsa olsun karşılanır. Sağlık sigortası bu özelliği ile olası yüksek meblağlı sağlık giderlerini karşılayarak, sigortalıların en zor anlarında en büyük yardımcısı olur.',
    body: [
      'Tamamlayıcı sağlık sigortaları ise SGK\'nın anlaşmalı olduğu özel hastanelerde hizmet almanızı sağlarken ortaya çıkacak olan farkların ödenmesini sağlayan çok faydalı ve pratik ve hesaplı bir sağlık sigortası ürünüdür.',
      'Ücretli ya da yıllık beyanname veren mükellefler, ödedikleri sigorta primini vergi matrahından da indirebilir. Bu imkandan yararlanabilmek için primlerin ait olunan vadelerde ödenmesi gerekir.',
    ],
  },
  {
    id: 'bireysel-emeklilik',
    idx: '09',
    title: 'Bireysel Emeklilik',
    kicker: 'BES — Devlet katkılı tasarruf sistemi',
    desc: 'Çalışma hayatınız süresince yaptığınız düzenli tasarrufların yatırıma yönlendirilmesini sağlayarak, oluşacak birikimle, çalışma döneminizde sahip olduğunuz yaşam standartlarını emeklilik döneminizde de devam ettirmeyi amaçlayan gönüllülüğe dayalı bir sistemdir.',
    body: [
      'BES, mevcut kamu sosyal güvenlik sisteminin tamamlayıcısı olan ve devlet katkısı ile desteklenen bir sistemdir.',
      'Bireysel Emeklilik Sisteminde emekli olmak için, ilk giriş tarihinizden itibaren 10 yıl süreyle sistemde bulunmak koşuluyla 56 yaşınızı tamamlamanız gerekir.',
      'Emeklilik sözleşmesi süresi içinde katkı payı tutarınızı değiştirebilirsiniz. Sözleşmeniz şirketimizde akdedilmiş ise birikimin başka bir şirkete aktarılabilmesi için sözleşmenin yürürlük tarihinden itibaren en az 2 yıl süreyle şirketimizde kalması gerekmektedir. Eğer sözleşmeniz başka şirketten aktarımla düzenlenmiş ise bu sözleşmenin tekrar aktarıma konu olabilmesi için şirketimizde en az 1 yıl kalması gerekmektedir.',
      'Emeklilik sözleşmesi süresi içinde katkı payı ödemeye ara verebilirsiniz. Bir sözleşme yılında en fazla 12 defa fon dağılım oranınızı değiştirebilirsiniz.',
      'Emekliliğe hak kazanmadan önce dilediğiniz anda sistemden ayrılabilirsiniz. Sistemden erken ayrılma durumunda birikimlerinizden ve Devlet katkılarının ödemeye konu olan kısımlarından stopaj ve varsa giriş aidatı kesintileri düşülür.',
      'Emekliliğe hak kazandıktan sonra toplu para, programlı ödeme ya da yıllık gelir sigortası seçeneklerinden birini seçebilir veya hesabınızdaki tutarı bu seçenekler arasında paylaştırabilirsiniz.',
    ],
  },
  {
    id: 'seyahat-sigortasi',
    idx: '10',
    title: 'Seyahat Sigortası',
    kicker: 'Yurt içi ve yurt dışı seyahat güvencesi',
    desc: 'Seyahat Sigortası, sizi ve sevdiklerinizi gerek iş gerekse tatil amaçlı seyahatlerinizde karşılaşabileceğiniz aksaklıklara karşı güvence altına alıyor.',
    body: [
      'Artı Oluşum Sigorta Seyahat Sigortası ile, müşterilerini seyahatleri sırasında beklenmedik ve ani durumlara karşı seyahat iptalinden bagaj kaybına, acil tıbbi nakilden kapkaça, tedavi masraflarından uçuş rötarına kadar geniş teminat altına alıyor.',
      'Kısa ve uzun süreli seyahatlerde geniş teminat seçenekleri sunan Tüm Dünya Seyahat Sigortasına hemen sahip olabilirsiniz.',
      'Seyahat Sigortası primi seçecek olduğunuz sigorta planına, seyahat tarihlerine ve doğum tarihine bağlı olarak farklılıklar göstermektedir.',
    ],
  },
  {
    id: 'nakliyat-sigortasi',
    idx: '11',
    title: 'Nakliyat Sigortası',
    kicker: 'Kara, deniz, hava, demir yolu',
    desc: 'Gemi, uçak, kamyon ya da tren gibi araçlarla taşınan mallar bu sigorta ile poliçede yer alan şartlar ve klozlar uyarınca bir kaza ya da bir olaya bağlı olarak fiziken zarar görmesi durumunda sigorta tarafından teminat altına alınır.',
    body: [],
  },
  {
    id: 'kurumsal-endustriyel',
    idx: '12',
    title: 'Kurumsal & Endüstriyel',
    kicker: 'İşletmenize özel sigorta çözümleri',
    desc: 'İşletmeniz için gerekli olabilecek; İnşaat tamamlama, Kefalet, All Risks, Sorumluluk, Makine Kırılması, Elektronik Cihaz, Enerji Sistemleri, Enerji Santralleri sigortaları gibi sigortaları içerir.',
    body: [
      'Her biri için öncelikle risk tespiti yapılıp sonrasında ihtiyaca yönelik sigorta çözümleri sunulur.',
    ],
  },
];

export const AGENCIES = [
  { name: 'Anadolu Sigorta',      logo: '/assets/agencies/anadolu-sigorta.svg' },
  { name: 'Aksigorta',            logo: '/assets/agencies/aksigorta.png' },
  { name: 'AXA Sigorta',          logo: '/assets/agencies/axa-sigorta.png' },
  { name: 'Allianz Sigorta',      logo: '/assets/agencies/allianz-sigorta.png' },
  { name: 'Ankara Sigorta',       logo: '/assets/agencies/ankara-sigorta.png' },
  { name: 'Mapfre Sigorta',       logo: '/assets/agencies/mapfre-sigorta.png' },
  { name: 'Türkiye Sigorta',      logo: '/assets/agencies/turkiye-sigorta.png' },
  { name: 'Doğa Sigorta',         logo: '/assets/agencies/doga-sigorta.png' },
  { name: 'Şeker Sigorta',        logo: '/assets/agencies/seker-sigorta.png' },
  { name: 'Ray Sigorta',          logo: '/assets/agencies/ray-sigorta.png' },
  { name: 'Türk Nippon Sigorta',  logo: '/assets/agencies/turk-nippon-sigorta.png' },
  { name: 'Neova Sigorta',        logo: '/assets/agencies/neova-sigorta.png' },
  { name: 'Zurich Sigorta',       logo: '/assets/agencies/zurich-sigorta.png' },
  { name: 'Sompo Sigorta',        logo: '/assets/agencies/sompo-sigorta.png' },
  { name: 'Hepİyi Sigorta',       logo: '/assets/agencies/hepiyi-sigorta.png' },
  { name: 'Quick Sigorta',        logo: '/assets/agencies/quick-sigorta.png' },
  { name: 'HDI Sigorta',          logo: '/assets/agencies/hdi-sigorta.png' },
  { name: 'GIG Sigorta',          logo: '/assets/agencies/gig-sigorta.png' },
  { name: 'Koru Sigorta',         logo: '/assets/agencies/koru-sigorta.png' },
  { name: 'Orient Sigorta',       logo: '/assets/agencies/orient-sigorta.png' },
  { name: 'BNP Paribas Cardif',   logo: '/assets/agencies/bnp-paribas-cardif.png' },
  { name: 'ViennaLife Emeklilik', logo: '/assets/agencies/viennalife-emeklilik.png' },
];

export const BRANCHES = [
  {
    id: 'ankara',
    type: 'Merkez',
    city: 'Ankara',
    label: 'Ankara Merkez',
    contact: 'AOL Sigorta Genel Müdürlük',
    addr: 'Aziziye Mah. Cinnah Cad. No:50/12, Çankaya / Ankara',
    phone: '+90 312 468 34 50',
    email: 'info@aol.gen.tr',
    mapQ: 'Aziziye+Mah.+Cinnah+Cad.+No:50/12+Çankaya+Ankara',
  },
  {
    id: 'denizli',
    type: 'Şube',
    city: 'Denizli',
    label: 'Denizli Şube',
    contact: 'AOL Sigorta Denizli',
    addr: 'Sümer Mah. 2482/2 Sok. Sky City No:4/1 D:73, Merkezefendi / Denizli',
    phone: '+90 258 264 68 69',
    email: 'info@aol.gen.tr',
    mapQ: 'Sümer+Mah.+2482/2+Sok.+Sky+City+No:4/1+Merkezefendi+Denizli',
  },
  {
    id: 'izmir-menemen',
    type: 'Şube',
    city: 'İzmir',
    label: 'İzmir Menemen Şube',
    contact: 'Tolgahan Aksular',
    addr: '30 Ağustos Mah. 7120 Sk. No: 2/1 Oyka Park Evleri (4. Noter Yanı) Egekent 2, Menemen / İzmir',
    phone: '0553 492 61 91',
    email: 'tolga.aksular@aol.gen.tr',
    mapQ: '30+Ağustos+Mah.+7120+Sk.+No:2/1+Egekent+2+Menemen+İzmir',
  },
  {
    id: 'izmir-cigli',
    type: 'Şube',
    city: 'İzmir',
    label: 'İzmir Çiğli Şube',
    contact: 'Vildan Öztürk',
    addr: 'Balatçık Mahallesi 8911/6 Sk. No:11/B, Çiğli / İzmir',
    phone: '0530 313 26 75',
    email: 'vildan.ozturk@aol.gen.tr',
    mapQ: 'Balatçık+Mahallesi+8911/6+Sk.+No:11/B+Çiğli+İzmir',
  },
  {
    id: 'corum-osmancik',
    type: 'Şube',
    city: 'Çorum',
    label: 'Çorum Osmancık Şube',
    contact: 'Uğur Aydı',
    addr: 'Yeni Mah. Alparslan Türkeş Cad. No:91/C/C, Osmancık / Çorum',
    phone: '0541 460 70 45',
    email: 'ugur.aydi@aol.gen.tr',
    mapQ: 'Alparslan+Türkeş+Cad.+No:91/C+Osmancık+Çorum',
  },
];

export const NAV = [
  { id: 'home', label: 'Ana Sayfa', path: '/' },
  { id: 'about', label: 'Hakkımızda', path: '/hakkimizda' },
  {
    id: 'products', label: 'Ürünler', path: '/urunler',
    children: PRODUCTS.map(p => ({ id: p.id, label: p.title, path: '/urunler/' + p.id, idx: p.idx }))
  },
  { id: 'agencies', label: 'Acenteliklerimiz', path: '/acenteliklerimiz' },
  { id: 'branches', label: 'Şubeler', path: '/subeler' },
  { id: 'contact', label: 'İletişim', path: '/iletisim' },
];
