export const COMPANY = {
  name: 'Artı Oluşum Sigorta',
  short: 'AOL Sigorta',
  slogan: 'Memnuniyetiniz için uzman bir takım',
  hq: {
    label: 'Ankara — Merkez',
    phone: '+90 312 468 34 50',
    addr: 'Aziziye Mah. Cinnah Cad. No:50/12, Çankaya / Ankara'
  },
  branch: {
    label: 'Denizli — Şube',
    phone: '+90 258 264 68 69',
    addr: 'Sümer Mah. 2482/2 Sok. Sky City No:4/1 D:73, Merkezefendi / Denizli'
  },
  email: 'info@aol.gen.tr',
  quoteEmail: 'ortak@aol.gen.tr',
  hours: 'Hafta içi 09:00 – 18:00 · Cumartesi 09:00 – 14:00',
  domain: 'aol.gen.tr'
};

export const STATS = [
  { n: '30',  s: 'yıla yakın', l: 'Sektör deneyimi' },
  { n: '22',  s: 'sigorta şirketi', l: 'Aktif acentelik' },
  { n: '12',  s: 'ana kategori', l: 'Ürün portföyü' },
  { n: '2',   s: 'şehir', l: 'Ankara + Denizli' },
];

export const PRODUCTS = [
  {
    id: 'kasko',
    idx: '01',
    title: 'Kasko Sigortası',
    kicker: 'Aracınız için tam koruma',
    desc: 'Çarpma, çalınma, yangın ve doğal afetlere karşı aracınızı kapsamlı şekilde güvence altına alır.',
    coverage: ['Kaza sonucu hasar', 'Çalınma ve yangın', 'Doğal afetler', 'Yedek araç hizmeti', 'Cam kırılması', 'Asistans'],
    forWhom: ['Yeni araç sahipleri', 'Günlük aracını kullananlar', 'Ticari araç sahipleri'],
  },
  {
    id: 'trafik-sigortasi',
    idx: '02',
    title: 'Trafik Sigortası',
    kicker: 'Yasal zorunluluk, hızlı işlem',
    desc: 'Karayolları Trafik Kanunu gereği zorunlu olan üçüncü şahıs mali mesuliyet sigortası.',
    coverage: ['Maddi hasar', 'Bedeni zarar', 'Ölüm ve sakatlık', 'Üçüncü şahıs teminatı'],
    forWhom: ['Tüm araç sahipleri (zorunlu)'],
  },
  {
    id: 'ferdi-kaza',
    idx: '03',
    title: 'Ferdi Kaza Sigortası',
    kicker: 'Kaza anında finansal güvence',
    desc: 'Kaza sonucu hayatını kaybetme, sürekli sakatlık ve geçici iş göremezlik hallerinde tazminat güvencesi.',
    coverage: ['Ölüm teminatı', 'Sürekli sakatlık', 'Geçici iş göremezlik', 'Tedavi giderleri', 'Gündelik hastane tazminatı'],
    forWhom: ['Çalışan bireyler', 'Serbest meslek sahipleri', 'Yüksek risk taşıyan meslekler'],
  },
  {
    id: 'hayat-sigortasi',
    idx: '04',
    title: 'Hayat Sigortası',
    kicker: 'Sevdikleriniz için uzun vadeli güvence',
    desc: 'Hayatınız boyunca ailenizi güvence altına alan, vefat ve maluliyet hallerinde destek sağlayan poliçeler.',
    coverage: ['Vefat teminatı', 'Maluliyet', 'Terminal hastalık', 'Borç koruma', 'Tasarruf bileşeni (opsiyonel)'],
    forWhom: ['Aile geçimini sağlayanlar', 'Kredi ve ipotek sahipleri', 'İş ortaklıkları (kilit kişi sigortası)'],
  },
  {
    id: 'konut-sigortasi',
    idx: '05',
    title: 'Konut Sigortası',
    kicker: 'Eviniz için kapsamlı koruma',
    desc: 'Yangın, hırsızlık, deprem ve su baskını gibi risklere karşı evinizi ve eşyalarınızı güvence altına alır.',
    coverage: ['Yangın ve duman', 'Hırsızlık', 'Deprem (isteğe bağlı)', 'Su baskını ve sel', 'İç su hasarları', 'Cam kırılması'],
    forWhom: ['Ev sahipleri', 'Kiracılar', 'Site yönetimleri'],
  },
  {
    id: 'isyeri-sigortasi',
    idx: '06',
    title: 'İşyeri Sigortası',
    kicker: 'İş alanınız için bütünleşik güvence',
    desc: 'Yangın, hırsızlık, makine kırılması ve iş kesintisi gibi ticari risklere karşı işyerinizi korur.',
    coverage: ['Yangın ve duman', 'Hırsızlık ve soygun', 'Cam kırılması', 'Makine kırılması', 'İş kesintisi', 'Mali mesuliyet'],
    forWhom: ['Esnaf ve KOBİ\'ler', 'Ofis ve mağaza sahipleri', 'Sanayi işletmeleri'],
  },
  {
    id: 'dask',
    idx: '07',
    title: 'DASK',
    kicker: 'Zorunlu deprem güvencesi',
    desc: 'Doğal Afet Sigortaları Kurumu tarafından yönetilen, konutlara zorunlu deprem sigortası.',
    coverage: ['Deprem sonucu yapısal hasar', 'Yangın, patlama ve tsunami', 'Zorunlu yasal kapsamlar', 'Kalıcı bina hasarları'],
    forWhom: ['Tüm konut sahipleri (zorunlu)', 'Kat mülkiyeti ve irtifak hakkı olanlar'],
  },
  {
    id: 'saglik-sigortasi',
    idx: '08',
    title: 'Sağlık Sigortası',
    kicker: 'Özel sağlık güvencesi',
    desc: 'Özel hastane ağı, serbest hekim seçimi, yurt içi ve yurt dışı teminat seçenekleri.',
    coverage: ['Yatarak tedavi', 'Ayakta tedavi', 'Doğum teminatı (opsiyonel)', 'Check-up', 'Yurt dışı kapsam', 'Diş paketi'],
    forWhom: ['Aileler', 'Çalışan profesyoneller', 'Şirket çalışan grupları'],
  },
  {
    id: 'bireysel-emeklilik',
    idx: '09',
    title: 'Bireysel Emeklilik',
    kicker: 'BES — Tasarruf ve yatırım',
    desc: 'Gönüllü katılım esasıyla, uzun vadeli tasarruf ve yatırım odaklı emeklilik planları.',
    coverage: ['%30 devlet katkısı', 'Esnek katkı payı', 'Fon tercih özgürlüğü', 'Birikim taşıma hakkı'],
    forWhom: ['18 yaş üstü bireyler', 'Kendi emeklilik planını kurmak isteyenler'],
  },
  {
    id: 'seyahat-sigortasi',
    idx: '10',
    title: 'Seyahat Sigortası',
    kicker: 'Yurt içi ve yurt dışı seyahat güvencesi',
    desc: 'Seyahat iptali, acil tıbbi yardım, bagaj kaybı ve hukuki yardım teminatlarını kapsayan seyahat poliçeleri.',
    coverage: ['Acil tıbbi yardım', 'Seyahat iptali ve kesintisi', 'Bagaj kaybı ve gecikme', 'Kişisel sorumluluk', 'Hukuki yardım', 'Uçuş gecikmesi'],
    forWhom: ['Yurt dışına çıkanlar', 'Sık seyahat edenler', 'Öğrenciler ve çalışma vizesi sahipleri'],
  },
  {
    id: 'nakliyat-sigortasi',
    idx: '11',
    title: 'Nakliyat Sigortası',
    kicker: 'Kara, deniz, hava, demir yolu',
    desc: 'Emtianın taşınması sırasında oluşabilecek hasar, kayıp ve çalınmalara karşı güvence.',
    coverage: ['Tam ziya', 'Hasar teminatı', 'Savaş ve grev', 'Yükleme/boşaltma'],
    forWhom: ['İthalatçı ve ihracatçı firmalar', 'Lojistik şirketleri', 'Toptan ticaret işletmeleri'],
  },
  {
    id: 'dogum-sigortasi',
    idx: '12',
    title: 'Doğum Sigortası',
    kicker: 'Hamilelik ve doğum özel ürünü',
    desc: 'Hamilelik takibi ve doğum giderlerini kapsayan, bekleme süresi olmayan özel ürün.',
    coverage: ['Hamilelik takibi', 'Normal ve sezaryen doğum', 'Yenidoğan bakımı', 'Doğum komplikasyonları'],
    forWhom: ['Aile planlaması yapanlar', 'Hamile anne adayları'],
  },
];

export const AGENCIES = [
  { name: 'Anadolu Sigorta',      logo: '/assets/agencies/anadolu-sigorta.svg' },
  { name: 'Aksigorta',            logo: '/assets/agencies/aksigorta.png' },
  { name: 'AXA Sigorta',          logo: '/assets/agencies/axa-sigorta.png' },
  { name: 'Allianz Sigorta',      logo: '/assets/agencies/allianz-sigorta.png' },
  { name: 'Ankara Sigorta',       logo: '/assets/agencies/ankara-sigorta.png' },
  { name: 'Mapfre Sigorta',       logo: '/assets/agencies/mapfre-sigorta.png' },
  { name: 'Türkiye Sigorta',      logo: '/assets/agencies/turkiye-sigorta.png' },
  { name: 'Doğa Sigorta',         logo: '/assets/agencies/doga-sigorta.png' },
  { name: 'Şeker Sigorta',        logo: '/assets/agencies/seker-sigorta.png' },
  { name: 'Ray Sigorta',          logo: '/assets/agencies/ray-sigorta.png' },
  { name: 'Türk Nippon Sigorta',  logo: '/assets/agencies/turk-nippon-sigorta.png' },
  { name: 'Neova Sigorta',        logo: '/assets/agencies/neova-sigorta.png' },
  { name: 'Zurich Sigorta',       logo: '/assets/agencies/zurich-sigorta.png' },
  { name: 'Sompo Sigorta',        logo: '/assets/agencies/sompo-sigorta.png' },
  { name: 'Hepİyi Sigorta',       logo: '/assets/agencies/hepiyi-sigorta.png' },
  { name: 'Quick Sigorta',        logo: '/assets/agencies/quick-sigorta.png' },
  { name: 'HDI Sigorta',          logo: '/assets/agencies/hdi-sigorta.png' },
  { name: 'GIG Sigorta',          logo: '/assets/agencies/gig-sigorta.png' },
  { name: 'Koru Sigorta',         logo: '/assets/agencies/koru-sigorta.png' },
  { name: 'Orient Sigorta',       logo: '/assets/agencies/orient-sigorta.png' },
  { name: 'BNP Paribas Cardif',   logo: '/assets/agencies/bnp-paribas-cardif.png' },
  { name: 'ViennaLife Emeklilik', logo: '/assets/agencies/viennalife-emeklilik.png' },
];

export const BRANCHES = [
  {
    id: 'ankara',
    type: 'Merkez',
    city: 'Ankara',
    label: 'Ankara Merkez',
    contact: 'AOL Sigorta Genel Müdürlük',
    addr: 'Aziziye Mah. Cinnah Cad. No:50/12, Çankaya / Ankara',
    phone: '+90 312 468 34 50',
    email: 'info@aol.gen.tr',
    mapQ: 'Aziziye+Mah.+Cinnah+Cad.+No:50/12+Çankaya+Ankara',
  },
  {
    id: 'denizli',
    type: 'Şube',
    city: 'Denizli',
    label: 'Denizli Şube',
    contact: 'AOL Sigorta Denizli',
    addr: 'Sümer Mah. 2482/2 Sok. Sky City No:4/1 D:73, Merkezefendi / Denizli',
    phone: '+90 258 264 68 69',
    email: 'info@aol.gen.tr',
    mapQ: 'Sümer+Mah.+2482/2+Sok.+Sky+City+No:4/1+Merkezefendi+Denizli',
  },
  {
    id: 'izmir-menemen',
    type: 'Şube',
    city: 'İzmir',
    label: 'İzmir Menemen Şube',
    contact: 'Tolgahan Aksular',
    addr: '30 Ağustos Mah. 7120 Sk. No: 2/1 Oyka Park Evleri (4. Noter Yanı) Egekent 2, Menemen / İzmir',
    phone: '0553 492 61 91',
    email: 'tolga.aksular@aol.gen.tr',
    mapQ: '30+Ağustos+Mah.+7120+Sk.+No:2/1+Egekent+2+Menemen+İzmir',
  },
  {
    id: 'izmir-cigli',
    type: 'Şube',
    city: 'İzmir',
    label: 'İzmir Çiğli Şube',
    contact: 'Vildan Öztürk',
    addr: 'Balatçık Mahallesi 8911/6 Sk. No:11/B, Çiğli / İzmir',
    phone: '0530 313 26 75',
    email: 'vildan.ozturk@aol.gen.tr',
    mapQ: 'Balatçık+Mahallesi+8911/6+Sk.+No:11/B+Çiğli+İzmir',
  },
  {
    id: 'corum-osmancik',
    type: 'Şube',
    city: 'Çorum',
    label: 'Çorum Osmancık Şube',
    contact: 'Uğur Aydı',
    addr: 'Yeni Mah. Alparslan Türkeş Cad. No:91/C/C, Osmancık / Çorum',
    phone: '0541 460 70 45',
    email: 'ugur.aydi@aol.gen.tr',
    mapQ: 'Alparslan+Türkeş+Cad.+No:91/C+Osmancık+Çorum',
  },
];

export const NAV = [
  { id: 'home', label: 'Ana Sayfa', path: '/' },
  { id: 'about', label: 'Hakkımızda', path: '/hakkimizda' },
  {
    id: 'products', label: 'Ürünler', path: '/urunler',
    children: PRODUCTS.map(p => ({ id: p.id, label: p.title, path: '/urunler/' + p.id, idx: p.idx }))
  },
  { id: 'agencies', label: 'Acenteliklerimiz', path: '/acenteliklerimiz' },
  { id: 'branches', label: 'Şubeler', path: '/subeler' },
  { id: 'contact', label: 'İletişim', path: '/iletisim' },
];
